using System;

namespace Parciales
{
    // This code was generated by a tool,
    // any changes made to this file will be discarded

    // Este código fue generado por una herramienta,
    // cualquier cambio hecho a este archivo será descartado
    public partial class Page
    {
        object Control1;
        object Control2;
        object Control3;

        void InitializeComponent()
        {
            Control1 = new object();
            Control2 = new object();
            Control3 = new object();
        }
    }
}

